@startuml
'https://plantuml.com/class-diagram
scale 2

skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members

class Personnage {
    -m_nom:String
    -m_race:Race
    -m_caracteristique:Caracteristique
    -m_inventaire:List<Armurerie>
    -m_equipement:Equipement
}

class Race {
    -m_nom:String
    -
}

class Caracteristique {
    -m_pv:Integer
    -m_force:Integer
    -m_dexterite:Integer
    -m_vitesse:Integer
    -m_initiative:Integer
}

@enduml